{% set name = "dask-cloudprovider" %}
{% set version = "2022.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask-cloudprovider/dask-cloudprovider-{{ version }}.tar.gz
  sha256: 090cf62de2891e8bd66802bc20d6766fa9886417b661deb49634fd44b2ae4cae

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask-ecs=dask_cloudprovider.cli.ecs:go

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - aiobotocore >=0.10.2
    - dask >=2.2.0
    - distributed >=2.3.1

test:
  imports:
    - dask_cloudprovider
  commands:
    - pip check
    - dask-ecs --help
  requires:
    - pip

about:
  home: https://cloudprovider.dask.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Cloud provider cluster managers for Dask distributed
  description: |
    Native Cloud integration for Dask. This library intends to allow people to create dask clusters on a
    given cloud provider with no set up other than having credentials.
  doc_url: https://cloudprovider.dask.org/
  dev_url: https://github.com/dask/dask-cloudprovider

extra:
  recipe-maintainers:
    - jacobtomlinson
    - mrocklin
