{% set name = "dask-cloudprovider" %}
{% set version = "2021.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/dask-cloudprovider/dask-cloudprovider-{{ version }}.tar.gz
  sha256: e6ea15098625daaf662350e69517cb2d9f9ec22f56217bd6cd3342989bfc88c2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - dask-ecs=dask_cloudprovider.cli.ecs:go

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - aiobotocore >=0.10.2
    - azure-cli-core >=2.15.1
    - azure-mgmt-compute >=18.0.0
    - azure-mgmt-network >=16.0.0
    - dask >=2.2.0
    - distributed >=2.3.1
    - google-api-python-client >=1.12.5
    - google-auth >=1.23.0

test:
  imports:
    - dask_cloudprovider
  commands:
    - pip check
    - dask-ecs --help
  requires:
    - pip

about:
  home: https://cloudprovider.dask.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Cloud provider cluster managers for Dask distributed
  description: |
    Native Cloud integration for Dask. This library intends to allow people to create dask clusters on a
    given cloud provider with no set up other than having credentials.
  doc_url: https://cloudprovider.dask.org/
  dev_url: https://github.com/dask/dask-cloudprovider

extra:
  recipe-maintainers:
    - jacobtomlinson
    - mrocklin
