travis:
  secure:
    BINSTAR_TOKEN: tI33lJJtkIeqOxrUTiNpXp/zR6Uf+MUoX9zXYfzKNf7s+hqrG7m85FDuQ+YSr6iADXsCaeJRJaACbVfLGU6+PCJ5I9L3pKnBxHKNt9K11HPJr8+u8HS2VDc0Tr71b6PcabtlcBKsVK0rynXywNDFjU9EQxgvxMd7H0uqb4xI/WX88atANOfYj6h2UOMzcO4WfD1S4HNMudrDfJUpLttEhzGeqKsr5XjgGD9zjyZ4H2RgNs7zox1I34Qst2xbfc/pV1789gepjAYktrHM0D6T2wUyXA90mQ27I4h7KDX7BoFXqZKfFLoT7XyoKc43sY9S/yiaosImIfKi5Ceo3uykGC3O1ek0YwILWKNDkQggvFpvozf+bhYhNR/cW0uQ0uE4rIxS3818YJZ2tiFXtHJ4LIDEh7aRQbNYHyaynwvavfGp2wTSCA0hM6EzYXcaULyLxZIUtewukwB/4U+GTm3imuRKJdCW7tHBIfU3ydESGMslr6es+MdKv6NHB8pslxesKgIn21LYV8ROhwqzj0B9fsB9iIBKm0Sew4Z4Fyo6DbSeaREJ2H64a8QhPebsnYzsjoMc94ZwmGVXpo32FVPuHPPInBTt2F5ygJYy+t68/cXjkLugTsBaIQfbKGUKa+Q2dcWFYLyPbRNibQC/R4tg4RvXm9DaF5CO0XdCHdufBs0=
conda_forge_output_validation: true
bot:
  automerge: true
